[DOCUMENTATION]
ORG_URL="https://series1.artx.one"

[[CURRENCIES]]
code="artone1"
issuer="GDT4OT5Z7FLK5UE7EBHSCN5JSW37T6MYYN2NLNVGIC4XPJKUJLBRGP6P"
display_decimals=7
name="FIRE"
desc="ARTX NFT"
image="https://ipfs.io/ipfs/QmNtLJDmXFe9d2g2J3VoJizBWw4jKRk6aKtGgHuQsWyZpY"
